### ISSUE TITLE
error while running mugio

### ISSUE THREAD

**Issue by BioInf2305** [pspealman/mugio#2]
First of all thank you very much for this nice and very useful tool. I was trying to apply your tool on my dataset to identify inverted repeat junction, and I came across the following error: 

  File "mugio.py", line 1814, in <module>
    if test_for_long_phred(phred_dict[uid]):
KeyError: 'c2b8230d-c571-48e3-a444-229e5ffa7c24'

Further, I confirmed that the read with this id "c2b8230d-c571-48e3-a444-229e5ffa7c24" is aligned and therefore, present in the "sam" as well as the "fastq" files. However, I noticed that the in the python script ("mugio.py") on the **line number 1743**, the script assumes that the new record in the fastq file should always starts with "@" and this is followed by the read id. Now this assumption holds true for all the cases except where the line for the quality score also starts with "@". And this is what I observed (see the image attached) for the line showing the quality score of the read with id "c2b8230d-c571-48e3-a444-229e5ffa7c24". Note that, I confirm by printing that, in the cases as described above, "uid" will be replaced by the line showing the quality score and as a consequence the original/true "uid" will not be added in the dictionary. 

![github_6](https://user-images.githubusercontent.com/58446112/88291392-72e83e00-ccf8-11ea-8e80-ab45f0aeebcf.png)

**Comment by pspealman** [comment]
Thanks for bringing this to my attention. 
I had, mistakenly, assumed the '@' was a protected character and wouldn't be used in the phred scoring, no luck.

 I'm looking into a different implementation to read in those scores presently - it should be a fast fix.

**Comment by BioInf2305** [comment]
Thank you for the quick response. I just put the "line_ct!=3:" alongside "line[0] == '@'" to make sure that the line with quality score does not enter this condition and it worked well on my data.

**Comment by pspealman** [comment]
Thanks for the suggestion, I came to a very similar conclusion with an additional check for the preceding line to feature consist of a '+'. 
Also thanks for your patience - there were a lot of places in the code that needed to be updated and checked.
